export const TAKELIST_CUSTOMER = 'TAKELIST_CUSTOMER';
export const TAKELIST_CUSTOMER__SUCCESS = 'TAKELIST_CUSTOMER__SUCCESS';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const EDIT_CUSTOMER__SUCCESS = 'EDIT_CUSTOMER__SUCCESS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER__SUCCESS = 'DELETE_CUSTOMER__SUCCESS';

export const ERROR_REQUEST = 'ERROR_REQUEST';
