export const TAKEORDER = 'TAKEORDER';
export const TAKEORDER__SUCCESS = 'TAKEORDER__SUCCESS';
export const TAKEORDER_DETAIL = 'TAKEORDER_DETAIL';
export const TAKEORDER_DETAIL__SUCCESS = 'TAKEORDER_DETAIL__SUCCESS';
export const CHANGESTATUS = 'CHANGESTATUS';
export const CHANGESTATUS__SUCCESS = 'CHANGESTATUS__SUCCESS';

export const ERRORREQUEST = 'ERRORREQUEST';
