export const TAKELIST_MENPAGE = 'TAKELIST_MENPAGE';

export const TAKELIST_MENPAGE_SUCCESS = 'TAKELIST_MENPAGE_SUCCESS';

export const TAKELIST_MENPAGE_ERROR = 'TAKELIST_MENPAGE_ERROR';

export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_PRODUCT__SUCCESS = 'FILTER_PRODUCT__SUCCESS';
export const FILTER_PRODUCT__ERROR = 'FILTER_PRODUCT__ERROR';
