export const TAKELIST_PAGE = 'TAKELIST_PAGE';
export const TAKELIST_TRENDING_PAGE = 'TAKELIST_TRENDING_PAGE';
export const TAKELIST_PAGE_SUCCESS = 'TAKELIST_PAGE_SUCCESS';

export const TAKELIST_PAGE_ERROR = 'TAKELIST_PAGE_ERROR';

export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_PRODUCT__SUCCESS = 'FILTER_PRODUCT__SUCCESS';
export const FILTER_PRODUCT__ERROR = 'FILTER_PRODUCT__ERROR';

export const BANNER_PAGE = 'BANNER_PAGE';

export const BANNER_PAGE_SUCCESS = 'BANNER_PAGE_SUCCESS';
