export const TAKE_DETAIL_PRODUCT = 'TAKE_DETAIL_PRODUCT';

export const TAKE_DETAIL_PRODUCT_SUCCESS = 'TAKE_DETAIL_PRODUCT_SUCCESS';
export const TAKE_DETAIL_PRODUCT_ERROR = 'TAKE_DETAIL_PRODUCT_ERROR';

export const ADD_TO_CART = 'ADD_TO_CART';
