export const TAKEDATA_MONTH = 'TAKEDATA_MONTH';
export const TAKEDATA_MONTH__SUCCESS = 'TAKEDATA_MONTH__SUCCESS';
export const TAKEDATA_YEAR = 'TAKEDATA_YEAR';
export const TAKEDATA_YEAR__SUCCESS = 'TAKEDATA_YEAR__SUCCESS';
export const ERROR_REQUEST = 'ERROR_REQUEST';
