export const REDUX_KEY = 'ResetPassWord';
export const RESETPASSWORD = 'RESETPASSWORD';

export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';

export const RESETPASSWORD_ERROR = 'RESETPASSWORD_ERROR';

export const RECIEVEEMAILCHANGE = 'RECIEVEEMAILCHANGE';

export const RECIEVEEMAILCHANGE_SUCCESS = 'RECIEVEEMAILCHANGE_SUCCESS';

export const RECIEVEEMAILCHANGE_ERROR = 'RECIEVEEMAILCHANGE_ERROR';
