export const TAKELISTIVENTORY = 'TAKELISTIVENTORY';
export const TAKELISTIVENTORYSUCCESS = 'TAKELISTIVENTORYSUCCESS';

export const ADDIVENTORY = 'ADDIVENTORY';

export const ADDIVENTORYSSUCCESS = 'ADDIVENTORYSSUCCESS';

export const EDITIVENTORY = 'EDITIVENTORY';
export const EDITIVENTORYSSUCCESS = 'EDITIVENTORYSSUCCESS';

export const ERRORREQUEST = 'ERRORREQUEST';

export const DELETE = 'DELETE';

export const DELETESUCCESS = 'DELETESUCCESS';
